### ISSUE TITLE
Github actions: put tests on github workflows

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#240]
### What
Put selene tests on github worflows using github actions.

### Why
Travis-CI become slow and queues about 30 mins each build before start.

### ToDo
- [x] Move travis test scripts to github-actions.
- [x] Check it works fine.

Additional steps
- [x] Save test results to github artifacts.
~Save selene screenshots to github artifacts.~ (will be added in another PR)
