### ISSUE TITLE
[tests] Get rid of `"start_page.html"` in `tests/resources` - replace it with raw code samples in each test. (from pr-review #237)

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#257]
### What
Get rid of `"start_page.html"` in tests in case it's too large page, it's difficult to read and contents many things while integration tests should be simple and use only small part of this page.

### Todo
- [x] Rewrite new tests which still use `"start_page.html"`.
- 1. tests/integration/condition__browser__have_url_test.py
- 2. tests/integration/browser__switch_to__alert_test.py
- [x] Finish todos in these modules
- [x] Delete "start_page.html" from `tests/resources`.
