### ISSUE TITLE
Code conventions

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#260]
### What
Add code conventions and linters for it.
### Why
In case to keep code style protected from new contributors and to keep project code quality at some level.

### Todo
- [ ] Write down Code conventions into CONTRIBUTING.md file

Consider to use one or few of:
- [ ] [pycodestyle](https://github.com/PyCQA/pycodestyle)
- [ ] [pylint](https://github.com/PyCQA/pylint)
- [ ] [we-make-python-code-style-guide](https://wemake-python-stylegui.de/en/latest/) with [flake8](https://flake8.pycqa.org/en/latest/manpage.html) in case it's a plugin for `flake8`.
- [ ] [black](https://github.com/psf/black) excludes `darker`
- [ ] [darker](https://github.com/akaihola/darker) excludes `black`

They all can be implemented together as CI-checkers, except `black` and `darker`.

**Comment by aleksandr-kotlyar** [comment]
"Darker" is much better than "Black". Not too ultimative and prefers single quote string instead of double quotes. As i know @yashaka you like single quotes more than double quotes.
