### ISSUE TITLE
Pycodestyle checker

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#264]
### Todo
- [x] Implement pycodestyle job to selene github-actions.
- [x] Agree on pycodestyle checks.
- [x] Fix pycodestyle issues.

### Resolution
PR #267

**Comment by aleksandr-kotlyar** [comment]
@yashaka i have fixed most common pycodestyle issues.
Need to consider the most difficult: do we ignore them in the whole selene project or do we fix them?

- `E402 module level import not at top of file`
- `E731 do not assign a lambda expression, use a def`

E402
I have discovered that `/selene/selene/__init__.py` uses some strange documentation with imports between it.
Does it still need in the same way?

E731
Lambdas - do we need them in assign?

Report: https://github.com/aleksandr-kotlyar/selene/runs/1665430347?check_suite_focus=true
```
/home/runner/work/selene/selene/selene/__init__.py:55:1: E402 module level import not at top of file
/home/runner/work/selene/selene/selene/__init__.py:79:1: E402 module level import not at top of file
/home/runner/work/selene/selene/selene/__init__.py:90:1: E402 module level import not at top of file
/home/runner/work/selene/selene/selene/__init__.py:112:1: E402 module level import not at top of file
/home/runner/work/selene/selene/selene/__init__.py:123:1: E402 module level import not at top of file
/home/runner/work/selene/selene/selene/__init__.py:219:1: E402 module level import not at top of file
/home/runner/work/selene/selene/selene/common/predicate.py:77:1: E731 do not assign a lambda expression, use a def
/home/runner/work/selene/selene/selene/common/predicate.py:90:1: E731 do not assign a lambda expression, use a def
/home/runner/work/selene/selene/selene/core/entity.py:1315:1: E402 module level import not at top of file
/home/runner/work/selene/selene/selene/support/shared/config.py:184:13: E731 do not assign a lambda expression, use a def
/home/runner/work/selene/selene/selene/support/shared/config.py:375:9: E731 do not assign a lambda expression, use a def
/home/runner/work/selene/selene/tests/unit/common/test_predicate.py:56:1: E402 module level import not at top of file
```

**Comment by yashaka** [comment]
E402 can't be fixed for now, because we have to refactor too much to make it work...

We have to ignore it, unless we break down entities to its own modules and find the way to have no conflicts in imports...

**Comment by aleksandr-kotlyar** [comment]
> E402 can't be fixed for now, because we have to refactor too much to make it work...
> 
> We have to ignore it, unless we break down entities to its own modules and find the way to have no conflicts in imports...

Okay, i understood. Let's move E402 discuss to #265. I will ignore E402 check for now.

**Comment by yashaka** [comment]
Regarding lambdas - i love them :+) And don't agree with PEP8 that they shouldn't be used when assigning. In some specific cases lambdas are more handy then defs, mainly in situations when we need to implement "curryable" functions (fn that returns fn that returns fn, etc.)

But in some cases we can remove them, and leave defs... I have to check all such cases...

**Comment by aleksandr-kotlyar** [comment]
> Regarding lambdas - i love them :+) And don't agree with PEP8 that they shouldn't be used when assigning. In some specific cases lambdas are more handy then defs, mainly in situations when we need to implement "curryable" functions (fn that returns fn that returns fn, etc.)
> 
> But in some cases we can remove them, and leave defs... I have to check all such cases...

Understood. Should i wait for it or just ignore E731 for now for making PR with pycodestyle checker viable?

**Comment by aleksandr-kotlyar** [comment]
I completed this issue. See PR #267 .

**Comment by aleksandr-kotlyar** [comment]
Resolved in #267
