### ISSUE TITLE
Codestyle: max-line-length

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#266]
# What to do in this issue?
- [x] Decide does we need this rule in selene codestyle checkers (example pycodestyle rule E501) - **Done** https://github.com/yashaka/selene/issues/266#issuecomment-802053762.
- [x] Define max-line-lent: **Done** 79 https://github.com/yashaka/selene/issues/266#issuecomment-802053762.

When max line length will be decided and defined:
- [x] Refactor whole project with this max-line-length **Done** in PR #295.

# Progress
- [x] 1. Refactored the project with 79 max-line-length in PR #295.
- [x] 2. Add "black" configuration check 79 max-line-length PR #297.
- [ ] 3. ~Enable E501 pycodestyle 79 chars max-line-length.~
- [x] 4. Set pylint 79 chars max-line-length. PR #298

**Comment by yashaka** [comment]
yes, let's follow the classic limitation from PEP8
I believe that this is very simple and efficient technique to code in a more readable way through decomposing "longer more complicated things" into "smaller and simpler".

**Comment by aleksandr-kotlyar** [comment]
Ok, so it will be <=79 line length.
