### ISSUE TITLE
upgrade to python 3.7 

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#288]
## What?
Upgrade selene codebase to 3.7 python version.

## Why?
The support of 3.6 is [ending](https://www.python.org/downloads/) at the end of current year 2021. And 3.7 version will live a little longer until year 2023.
![image](https://user-images.githubusercontent.com/17043964/109419303-caacfd00-79dd-11eb-8b6b-afd89a3674fe.png)

## How?
Update codebase by using [pyupgrade](https://github.com/asottile/pyupgrade) tool in complex with [pyupgrade-directories](https://github.com/domdfcoding/pyupgrade-directories).

You can choose any other instruments to do refactoring up to 3.7.

## Todo
- [ ] refactor the codebase up to 3.7 python.

P.S. Also, it will be nice to have a pre-commit-hook which will control the code after refactoring.
- [ ] add pre-commit hook with `pyupgrade`; (optional - could be implemented later)
- [ ] add github-action with pre-commit checks. (optional - could be implemented later)

**Comment by EmadDeve20** [comment]
hi, I am a Noob programmer and I searching for an issue for learning.
can I work on your code?

**Comment by aleksandr-kotlyar** [comment]
> hi, I am a Noob programmer and I searching for an issue for learning.
> can I work on your code?

Hi @EmadDeve20! Sure, you can try it out!

**Comment by sandipan898** [comment]
Hi, Is this issue still open to fix or someone has already fixed it?

**Comment by aleksandr-kotlyar** [comment]
> Hi, Is this issue still open to fix or someone has already fixed it?

Issue is still open to be done.
