### ISSUE TITLE
Prepare to good-first-issue

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#289]
### What
Prepare selene project to [good-first-issue](https://github.com/deepsourcelabs/good-first-issue) criteria.

### Why
In case to attract new contributors.

### Todo
Go through check-list from good-first issue readme and complete each point.

- [x] Our goal is to narrow down projects for new open-source contributors. To maintain the quality of projects in Good First Issue, please make sure your GitHub repository meets the following criteria:

  - [x] At least three issues with the `good first issue` label. This label is already present on all repositories by default. If not, you can follow the steps [here](https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests).

  - [x] Detailed setup instructions for the project.

  - [x] CONTRIBUTING.md

  - [x] Actively maintained.

- [x] Add your repository's path in [data/repositories.toml](data/repositories.toml).

- [x] Create a new pull-request. Please add the link to the issues page of the repository in the PR description. Once the pull request is merged, the changes will be live on [goodfirstissue.dev](https://goodfirstissue.dev/).

**Comment by aleksandr-kotlyar** [comment]
@yashaka our repo is in the good-first-issue list for now!
https://goodfirstissue.dev/language/python
The most recent commit into master selene has - the higher it's rank in the list. 
![image](https://user-images.githubusercontent.com/17043964/110235104-650dc300-7f3f-11eb-83f2-ae78e2ea9310.png)
